### ISSUE TITLE
Changing the behavior when reaching the set lowBatLimitTHPL

### ISSUE THREAD

**Issue by mr-p666** [kc-GitHub/Wettersensor#11]
Hej Dirk,

can you please change the behavior when reaching the set lowBatLimitTHPL.
At the moment it reports battery low when the configured value is reached and when the value is exceeded by 0.01 again, it reports battery ok again.
The power fluctuations cause a constant back and forth between the 'low' and 'ok' trigger as long as the fluctuations persist to this limit.
Is it possible to change only back to 'ok', when the current voltage value is at least 0,1V higher instead of current "everything higher than the threshold value"?

Thx a lot! :-)

**Comment by kc-GitHub** [comment]
now there is a hysteresis of 0.2 v for reset battery low status after increasing battery voltage
